### ISSUE TITLE
URL in Macaque ```Datahelpers.py``` portion is broken

### ISSUE THREAD

**Issue by thejasvibr** [earthspecies/cocktail-party-problem#3]
Hi Peter,
Cool stuff with the BioCPP - am trying to see if it'll be relevant to my work with echolocating bat groups. 
 
I've tried to replicate training with BioCPP with the Macaque dataset - and failed to go past Step 2 in the README. It appears as though the URL (referenced to ```self.url``` ) in  ```DataHelpers.py```  line 17 is broken. 

This is the error I get on running the classifier part of Step 3:

```
Traceback (most recent call last):
  File "DataGenerator.py", line 198, in <module>
    X, Y = generate_labeled_waveforms(animal,
  File "DataGenerator.py", line 35, in generate_labeled_waveforms
    X, Y = loader.run(balance=kwargs['balance'])
  File "C:\Users\..\cocktail-party-problem\DataHelpers.py", line 91, in run
    data_df = self.fixed_dataframe()
  File "C:\Users\..\cocktail-party-problem\DataHelpers.py", line 52, in fixed_dataframe
    dataframe = self.construct_dataframe()
  File "C:\Users\..\cocktail-party-problem\DataHelpers.py", line 24, in construct_dataframe
    path = untar_data(self.url)
  File "C:\Users\..\anaconda3\envs\sourcesep\lib\site-packages\fastai\data\external.py", line 124, in untar_data
    return d.get(url, force=force_download, extract_key=c_key)
  File "C:\Users\..\anaconda3\envs\sourcesep\lib\site-packages\fastdownload\core.py", line 121, in get
    self.download(url, force=force)
  File "C:\Users\..\anaconda3\envs\sourcesep\lib\site-packages\fastdownload\core.py", line 96, in download
    return download_and_check(url, urldest(url, self.arch_path()), self.module, force)
  File "C:\Users\..\anaconda3\envs\sourcesep\lib\site-packages\fastdownload\core.py", line 65, in download_and_check
    res = download_url(url, fpath)
  File "C:\Users\..\anaconda3\envs\sourcesep\lib\site-packages\fastdownload\core.py", line 23, in download_url
    return urlsave(url, dest, reporthook=progress if show_progress else None, timeout=timeout)
  File "C:\Users\..\anaconda3\envs\sourcesep\lib\site-packages\fastcore\net.py", line 178, in urlsave
    nm,msg = urlretrieve(url, dest, reporthook, timeout=timeout)
  File "C:\Users\..\anaconda3\envs\sourcesep\lib\site-packages\fastcore\net.py", line 143, in urlretrieve
    with contextlib.closing(urlopen(url, data, timeout=timeout)) as fp:
  File "C:\Users\..\anaconda3\envs\sourcesep\lib\site-packages\fastcore\net.py", line 105, in urlopen
    return _opener.open(urlwrap(url, data=data, headers=headers), timeout=timeout)
  File "C:\Users\..\anaconda3\envs\sourcesep\lib\urllib\request.py", line 531, in open
    response = meth(req, response)
  File "C:\Users\..\anaconda3\envs\sourcesep\lib\urllib\request.py", line 640, in http_response
    response = self.parent.error(
  File "C:\Users\..\anaconda3\envs\sourcesep\lib\urllib\request.py", line 569, in error
    return self._call_chain(*args)
  File "C:\Users\..\anaconda3\envs\sourcesep\lib\urllib\request.py", line 502, in _call_chain
    result = func(*args)
  File "C:\Users\..\anaconda3\envs\sourcesep\lib\urllib\request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
```

Could you please provide an up to date link to the required data in line 17?

**Comment by pcbermant** [comment]
Hi there, thanks for letting me know! I've updated the URL (https://storage.googleapis.com/ml-bioacoustics-datasets/macaques_24414Hz.zip) in the script.

Please let me know if this doesn't work. Thanks!
