### ISSUE TITLE
.npy file pre-requisite

### ISSUE THREAD

**Issue by thejasvibr** [earthspecies/cocktail-party-problem#4]
On running the ```DataGenerator.py``` module from command line with:
```
python DataGenerator.py --animal Macaque --data_directory Data --config config.json --os Windows --objective Classification --regime Closed
```

an error pops up saying there are no .npy files found in the 'Data' directory.

```
Traceback (most recent call last):
  File "DataGenerator.py", line 213, in <module>
    X_closed = [row for row in np.load(root+'Waveforms/X_closed.npy')]
  File "C:\..\envs\sourcesep\lib\site-packages\numpy\lib\npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'Macaque/Data/Waveforms/X_closed.npy'
```

**Comment by pcbermant** [comment]
Try removing the Data/ directory and running the command again. There are a few exceptions I haven't accounted for.
